apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
        - name: chat-app-container
          image: diaaqassem1/chatapp:v0.3
          ports:
            - containerPort: 5000
            - containerPort: 5001 
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DB_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: SECRET_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: GOOGLE_SECRET
