apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
spec:
  selector:
    app: chat-app
  ports:
    - name: app
      port: 5000
      targetPort: 5000
      nodePort: 30000
    - name: gateway
      port: 5001
      targetPort: 5001
      nodePort: 30001 
  type: NodePort

